https://github.com/aspnet/live.asp.net/issues/112
aspnet/live.asp.net pull request #130
Opened 2017-04-04 13:24 UTC by ganniaiuei

2017-04-04 13:24 UTC, dnfclas commented
@__ganniaiuei__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla2.dotnetfoundation.org.

It will cover your contributions to all .NET Foundation-managed open source projects.
_Thanks,
.NET Foundation Pull Request Bot_

2017-04-04 13:30 UTC, dnfclas commented
__@ganniaiuei__, thanks for signing the contribution license agreement. We will now validate the agreement and then the pull request.
<br />_Thanks, .NET Foundation Pull Request Bot_

2017-04-04 16:57 UTC, hishamco requested changes

2017-04-04 16:57 UTC, hishamco commented on src/live.asp.net/AppSettings.cs
> +		public string CDNUrl { get; set; }
You miss one space before

2017-04-04 16:57 UTC, hishamco commented on src/live.asp.net/Startup.cs
> +using Microsoft.Net.Http.Headers;
Sort the `using`

2017-04-04 16:57 UTC, hishamco commented on src/live.asp.net/Startup.cs
> +							MaxAge = TimeSpan.FromDays(365)
I think we can use:
```csharp
var now = DateTime.Now;
MaxAge = now.AddYears(1) - now;
```
instead

2017-04-04 16:57 UTC, hishamco commented on src/live.asp.net/TagHelpers/CDNSourcingTagHelper.cs
> +using Microsoft.Extensions.FileProviders;
Sorting!!

2017-04-04 16:57 UTC, hishamco commented on src/live.asp.net/TagHelpers/CDNSourcingTagHelper.cs
> +	[HtmlTargetElement("image", Attributes = "fromCDN")]
IMHO `useCDN` may be better

2017-04-04 16:57 UTC, hishamco commented on src/live.asp.net/TagHelpers/CDNSourcingTagHelper.cs
> +	[HtmlTargetElement("link", Attributes = "[rel='stylesheet'],fromCDN")]
Add space after the comma

2017-04-04 16:57 UTC, hishamco commented on src/live.asp.net/TagHelpers/CDNSourcingTagHelper.cs
> +        {
Please format the file properly

2017-04-04 16:57 UTC, hishamco commented on src/live.asp.net/TagHelpers/CacheBustingTagHelper.cs
> +        {
Check the format again ..

2017-04-05 07:55 UTC, ganniaiuei commented on src/live.asp.net/AppSettings.cs
> +		public string CDNUrl { get; set; }
maybe some different settings in the editor, I didnt' see any space in my editor. Should I check something specific?

2017-04-05 07:56 UTC, ganniaiuei commented on src/live.asp.net/Startup.cs
> +							MaxAge = TimeSpan.FromDays(365)
ok

2017-04-05 07:56 UTC, ganniaiuei commented on src/live.asp.net/TagHelpers/CDNSourcingTagHelper.cs
> +	[HtmlTargetElement("image", Attributes = "fromCDN")]
ok

2017-04-05 07:57 UTC, ganniaiuei commented on src/live.asp.net/TagHelpers/CDNSourcingTagHelper.cs
> +        {
also, in my editor the file is properly formatted.

2017-04-05 08:05 UTC, hishamco commented on src/live.asp.net/AppSettings.cs
> +		public string CDNUrl { get; set; }
If you look closely here in the last line you will recognize there's one space missing before `public`, perhaps the Tab Size in VS is different

2017-04-05 08:54 UTC, hishamco commented
I think we have spacing issue here 😞

2017-04-05 08:58 UTC, alexwiese commented
Looks like a mixture of spaces and tabs to me.  Please reformat using spaces everywhere.

2017-04-05 09:43 UTC, ganniaiuei commented
Ok, I've applied a formatting with spaces and the tabs are gone.

2019-10-30 00:12 UTC, closed without merging